services:
  postgis:
    image: moritzdenk/triptailor-db #kartoza/postgis:17-3.5
    container_name: triptailor_db2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: osm_data
    ports:
      - "9876:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d osm_data" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my_network

  web:
    image: moritzdenk/triptailor-backend:latest
    ports:
      - "5001:5001"
    environment:
      DB_HOST: postgis
      DB_NAME: osm_data
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_PORT: 5432
    depends_on:
      postgis:
        condition: service_healthy
    networks:
      - my_network

  webclient:
    image: moritzdenk/triptailor-webclient:latest
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    env_file:
      - .env
    restart: on-failure
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgis_data: